# Generated by Django 5.1 on 2024-10-20 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MgiCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_signal', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('idea_candle', models.ImageField(blank=True, null=True, upload_to='idea_candles/')),
                ('line_graph_candle', models.ImageField(blank=True, null=True, upload_to='line_graph_candles/')),
                ('signal_candle', models.ImageField(blank=True, null=True, upload_to='signal_candles/')),
                ('two_hour_candle', models.ImageField(blank=True, null=True, upload_to='two_hour_candles/')),
                ('monday_candle', models.ImageField(blank=True, null=True, upload_to='monday_candles/')),
                ('tuesday_candle', models.ImageField(blank=True, null=True, upload_to='tuesday_candles/')),
                ('wednesday_candle', models.ImageField(blank=True, null=True, upload_to='wednesday_candles/')),
                ('thursday_candle', models.ImageField(blank=True, null=True, upload_to='thursday_candles/')),
                ('friday_candle', models.ImageField(blank=True, null=True, upload_to='friday_candles/')),
                ('saturday_candle', models.ImageField(blank=True, null=True, upload_to='saturday_candles/')),
                ('sunday_candle', models.ImageField(blank=True, null=True, upload_to='sunday_candles/')),
                ('pips_lost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pips_gained', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('hour_candle', models.ImageField(blank=True, null=True, upload_to='hour_candles/')),
                ('entry_candle', models.ImageField(blank=True, null=True, upload_to='entry_candle/')),
                ('breakeven_candle', models.ImageField(blank=True, null=True, upload_to='breakeven_candle/')),
                ('take_profit_candle', models.ImageField(blank=True, null=True, upload_to='take_profit_candle/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candle_pattern', models.CharField(blank=True, choices=[('Engulfing', 'Engulfing Candle'), ('Small Body', 'Small Candle'), ('Pinbar', 'Pin bar Candle')], max_length=20, null=True)),
                ('fibonacci_level', models.CharField(blank=True, choices=[('38.2%', '38.2%'), ('50%', '50%'), ('61.8%', '61.8%'), ('78.6%', '78.6%')], max_length=5, null=True)),
                ('session', models.CharField(blank=True, choices=[('London', 'London Session'), ('Newyork', 'New York Session')], max_length=15, null=True)),
                ('currency_pair', models.CharField(blank=True, max_length=6, null=True)),
                ('five_min_order_block', models.BooleanField(blank=True, default=False, null=True)),
                ('flip_four_hour_candle', models.BooleanField(blank=True, default=False, null=True)),
                ('four_hour_break_of_structure', models.BooleanField(blank=True, default=False, null=True)),
                ('five_min_break_of_structure', models.BooleanField(blank=True, default=False, null=True)),
                ('change_color_ut_alert', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mgi candle',
                'verbose_name_plural': 'Mgi candles',
            },
        ),
    ]
